<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>VehicleRaidFramework</AssemblyName>
    <RootNamespace>VehicleRaidFramework</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\Assemblies\</OutputPath>
    <LangVersion>latest</LangVersion>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <!-- RimWorld Core -->
  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\..\RimWorldWin64_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>..\..\..\RimWorldWin64_Data\Managed\Assembly-CSharp-firstpass.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\..\RimWorldWin64_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>..\..\..\RimWorldWin64_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>..\..\..\RimWorldWin64_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <!-- Harmony -->
    <Reference Include="0Harmony">
      <HintPath>..\..\Harmony\Current\Assemblies\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <!-- Vehicle Framework -->
    <Reference Include="Vehicles">
      <HintPath>..\..\vehicle framework\1.6\Assemblies\Vehicles.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SmashTools">
      <HintPath>..\..\vehicle framework\1.6\Assemblies\SmashTools.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
